---
abstract: 'Plugin for customised log timestamps'
author:
  - 'Nic Sandfield <niczero@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.140640'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-Log-Timestamp
no_index:
  directory:
    - t
    - inc
    - test
requires:
  Mojar: '1.062'
  Mojolicious: '3.33'
  perl: '5.010001'
resources:
  bugtracker: http://github.com/niczero/mojolicious-plugin-log-timestamp/issues
  license: http://www.opensource.org/licenses/artistic-license-2.0
  repository: http://github.com/niczero/mojolicious-plugin-log-timestamp
version: 0.023
